# Imbalanced dataset

### A dataset with an unequal class distribuitiom

In [1]:
import numpy as np
import pandas as pd

In [5]:
# Loading dataset to pandas dataframe

credit_card_df = pd.read_csv('/Users/edmaurogoma/studyspace/ML/mk_path/datasets/credit_data.csv')
credit_card_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [6]:
credit_card_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [7]:
credit_card_df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [8]:
# distribuition of the two classes
credit_card_df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

This is a mighty imbalanced dataset

0 -> Legit Transactions
1 -> Fraudlent Transactions

In [9]:
# Separating the legit and fraudlent transactions

legit = credit_card_df[credit_card_df.Class == 0]
fraud = credit_card_df[credit_card_df.Class == 1]

In [10]:
print(legit.shape)

(284315, 31)

In [11]:
print(fraud.shape)

(492, 31)

Under-sampling

### Build a sample dataset simular distribuition of legit and fraudlent transactions

##### Number of #Fraudlent transactions -> 492

In [12]:
legit_sample = legit.sample(n = 492)
legit_sample

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
83337,59801.0,-5.133071,-6.792531,1.086572,0.744639,1.293364,-0.490484,-0.057537,0.703989,0.535520,...,0.856959,-0.229499,2.958440,-0.372960,-0.186480,0.698711,-0.371605,0.267684,900.51,0
175258,122260.0,1.757619,-1.561914,-0.826433,-0.352028,-1.112266,-0.129697,-0.727577,-0.000021,0.136224,...,-0.542371,-1.541931,0.358929,0.394851,-0.811776,0.199534,-0.064451,-0.002250,209.92,0
160336,113259.0,-0.257351,0.974304,-2.282105,-2.223551,3.577787,2.726243,1.049256,0.620352,-0.361372,...,0.211219,0.775913,-0.209645,0.751959,-0.223793,0.113857,0.524360,0.320265,0.77,0
28087,34850.0,1.352409,-1.320657,0.760664,-1.511821,-1.515177,0.432926,-1.570374,0.338961,-1.710212,...,0.040366,0.498500,0.052612,-0.322426,0.125212,-0.058728,0.073216,0.009443,20.00,0
248828,154111.0,0.171669,0.421080,0.784815,1.001171,-0.302610,0.673856,-0.408939,0.235871,0.496446,...,0.447385,1.469978,0.086745,0.738270,-1.612884,-0.047026,0.124358,0.303415,13.53,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210225,137890.0,1.820117,-0.516676,-0.421484,0.217824,0.071831,1.223188,-0.790150,0.507222,1.040924,...,-0.144315,-0.164256,0.573577,-1.328864,-0.948227,0.245889,0.039524,-0.057815,3.90,0
75454,56076.0,-1.674120,-1.442408,1.704155,0.903209,-0.067247,0.226164,0.380401,0.146984,0.094392,...,0.249824,0.036133,0.761242,-0.434376,-0.034641,0.409080,-0.017446,0.172642,337.75,0
205213,135637.0,2.236829,-0.744199,-1.511870,-0.983278,-0.409334,-1.011334,-0.409735,-0.294523,-0.429785,...,0.415923,1.147025,0.024405,0.773183,0.204121,0.037810,-0.049071,-0.060429,15.00,0
139346,83107.0,-0.436725,1.113415,1.717211,0.037608,-0.163687,-1.061672,0.775580,-0.135226,-0.544036,...,-0.196153,-0.466647,0.012006,0.714908,-0.209057,0.048139,0.270639,0.126169,4.48,0
258591,158724.0,2.064346,-0.037240,-1.056988,0.416345,-0.136652,-1.216820,0.190988,-0.341828,0.523541,...,-0.288158,-0.687258,0.341104,0.049413,-0.295164,0.195137,-0.069712,-0.059830,0.46,0

In [13]:
print(legit_sample.shape)

(492, 31)

#### Concatenate the two dataframes

In [16]:
new_dataset = pd.concat([legit_sample, fraud], axis = 0)
new_dataset

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
83337,59801.0,-5.133071,-6.792531,1.086572,0.744639,1.293364,-0.490484,-0.057537,0.703989,0.535520,...,0.856959,-0.229499,2.958440,-0.372960,-0.186480,0.698711,-0.371605,0.267684,900.51,0
175258,122260.0,1.757619,-1.561914,-0.826433,-0.352028,-1.112266,-0.129697,-0.727577,-0.000021,0.136224,...,-0.542371,-1.541931,0.358929,0.394851,-0.811776,0.199534,-0.064451,-0.002250,209.92,0
160336,113259.0,-0.257351,0.974304,-2.282105,-2.223551,3.577787,2.726243,1.049256,0.620352,-0.361372,...,0.211219,0.775913,-0.209645,0.751959,-0.223793,0.113857,0.524360,0.320265,0.77,0
28087,34850.0,1.352409,-1.320657,0.760664,-1.511821,-1.515177,0.432926,-1.570374,0.338961,-1.710212,...,0.040366,0.498500,0.052612,-0.322426,0.125212,-0.058728,0.073216,0.009443,20.00,0
248828,154111.0,0.171669,0.421080,0.784815,1.001171,-0.302610,0.673856,-0.408939,0.235871,0.496446,...,0.447385,1.469978,0.086745,0.738270,-1.612884,-0.047026,0.124358,0.303415,13.53,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [17]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
83337,59801.0,-5.133071,-6.792531,1.086572,0.744639,1.293364,-0.490484,-0.057537,0.703989,0.535520,...,0.856959,-0.229499,2.958440,-0.372960,-0.186480,0.698711,-0.371605,0.267684,900.51,0
175258,122260.0,1.757619,-1.561914,-0.826433,-0.352028,-1.112266,-0.129697,-0.727577,-0.000021,0.136224,...,-0.542371,-1.541931,0.358929,0.394851,-0.811776,0.199534,-0.064451,-0.002250,209.92,0
160336,113259.0,-0.257351,0.974304,-2.282105,-2.223551,3.577787,2.726243,1.049256,0.620352,-0.361372,...,0.211219,0.775913,-0.209645,0.751959,-0.223793,0.113857,0.524360,0.320265,0.77,0
28087,34850.0,1.352409,-1.320657,0.760664,-1.511821,-1.515177,0.432926,-1.570374,0.338961,-1.710212,...,0.040366,0.498500,0.052612,-0.322426,0.125212,-0.058728,0.073216,0.009443,20.00,0
248828,154111.0,0.171669,0.421080,0.784815,1.001171,-0.302610,0.673856,-0.408939,0.235871,0.496446,...,0.447385,1.469978,0.086745,0.738270,-1.612884,-0.047026,0.124358,0.303415,13.53,0

In [18]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [19]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64